apiVersion: v1
kind: Service
metadata:
  name: devops-api-service
spec:
  type: NodePort
  selector:
    app: devops-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30030   # Port pour acc√©der depuis ton PC
