name: SonarCloud Scan

on:
  push:
    branches: ["main", "feat/express-app"]
  pull_request:
    branches: ["main", "feat/express-app"]

jobs:
  sonar:
    name: SonarCloud Scan
    runs-on: windows-latest

    steps:
      # 1️⃣ Checkout du code
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important pour Sonar

      # 2️⃣ Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3️⃣ Installer les dépendances
      - name: Install dependencies
        run: npm install
        working-directory: devops-api

      # 4️⃣ Lancer SonarCloud Scan
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        working-directory: devops-api
