name: SonarCloud Scan

on:
  push:
    branches: ["main", "feat/express-app"]
  pull_request:
    branches: ["main", "feat/express-app"]

jobs:
  sonar:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important pour Sonar

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: devops-api

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: devops-api
          args: >
            -Dsonar.projectKey=hadil6_devops-project-hadil
            -Dsonar.organization=hadil6devopsproject-hadil
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
